CREATE TABLE `dependents` (
  `EMPID` double NOT NULL,
  `DEPID` double NOT NULL,
  `DEP_CNIC` double NOT NULL,
  `DEP_FNAME` varchar(20) NOT NULL,
  `DEP_LNAME` varchar(20) NOT NULL,
  `DOB` date NOT NULL,
  `GENDER` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `doctor` (
  `DOCID` double NOT NULL,
  `DOC_CNIC` double NOT NULL,
  `DOC_FNAME` varchar(20) NOT NULL,
  `DOC_LNAME` varchar(20) NOT NULL,
  `DOC_EMAIL` varchar(20) NOT NULL,
  `DOC_CONTACT` double NOT NULL,
  `DOB` date NOT NULL,
  `GENDER` varchar(10) NOT NULL,
  `SPECIALIZATION` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `doctor_assistant` (
  `DA_ID` int(11) NOT NULL,
  `TOKENID` double NOT NULL,
  `BP` varchar(10) DEFAULT NULL,
  `TEMPERATURE` int(11) DEFAULT NULL,
  `PULSE` int(11) DEFAULT NULL,
  `GLUCOSE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `employee` (
  `EMPID` double NOT NULL,
  `EMP_FNAME` varchar(20) NOT NULL,
  `EMP_LNAME` varchar(20) NOT NULL,
  `EMP_CNIC` double NOT NULL,
  `DESIGNATION` varchar(20) NOT NULL,
  `GENDER` varchar(10) NOT NULL,
  `EMP_EMAIL` varchar(50) DEFAULT NULL,
  `DOB` date NOT NULL,
  `EMP_CONTACT` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `general_checkup` (
  `EMPID` double NOT NULL,
  `DEPID` double DEFAULT NULL,
  `SLIPID` double NOT NULL,
  `DOCID` double NOT NULL,
  `VISIT_DATE` date DEFAULT curdate(),
  `VISIT_TIME` time DEFAULT curtime(),
  `VENDOR` varchar(5000) DEFAULT NULL,
  `DIAGNOSIS` varchar(5000) DEFAULT NULL,
  `REASON` varchar(100) NOT NULL,
  `MEDICINE` varchar(5000) DEFAULT NULL,
  `TOKENID` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `token` (
  `TOKENID` double NOT NULL,
  `EMPID` double NOT NULL,
  `DEPID` double DEFAULT NULL,
  `VISIT_DATE` date NOT NULL DEFAULT curdate(),
  `VISIT_TIME` time NOT NULL DEFAULT curtime(),
  `DOCID` double NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `dependents`
  ADD PRIMARY KEY (`DEPID`),
  ADD KEY `FK_EMP_DEP` (`EMPID`);


ALTER TABLE `doctor`
  ADD PRIMARY KEY (`DOCID`);


ALTER TABLE `doctor_assistant`
  ADD PRIMARY KEY (`DA_ID`),
  ADD KEY `fk_tokenid` (`TOKENID`);

ALTER TABLE `employee`
  ADD PRIMARY KEY (`EMPID`);

ALTER TABLE `general_checkup`
  ADD PRIMARY KEY (`SLIPID`),
  ADD KEY `FK_SLIP_DEP` (`DEPID`),
  ADD KEY `FK_SLIP_DOC` (`DOCID`),
  ADD KEY `FK_SLIP_EMP` (`EMPID`),
  ADD KEY `FK_SLIP_TOKEN` (`TOKENID`);

ALTER TABLE `token`
  ADD PRIMARY KEY (`TOKENID`),
  ADD KEY `FK_TOKEN_DEP` (`DEPID`),
  ADD KEY `FK_TOKEN_DOC` (`DOCID`),
  ADD KEY `FK_TOKEN_EMP` (`EMPID`);

ALTER TABLE `dependents`
  MODIFY `DEPID` double NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

ALTER TABLE `doctor`
  MODIFY `DOCID` double NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

ALTER TABLE `doctor_assistant`
  MODIFY `DA_ID` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `employee`
  MODIFY `EMPID` double NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;


ALTER TABLE `general_checkup`
  MODIFY `SLIPID` double NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=87;

ALTER TABLE `token`
  MODIFY `TOKENID` double NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;

ALTER TABLE `dependents`
  ADD CONSTRAINT `FK_EMP_DEP` FOREIGN KEY (`EMPID`) REFERENCES `employee` (`EMPID`);


ALTER TABLE `doctor_assistant`
  ADD CONSTRAINT `fk_tokenid` FOREIGN KEY (`TOKENID`) REFERENCES `token` (`TOKENID`);

ALTER TABLE `general_checkup`
  ADD CONSTRAINT `FK_SLIP_DEP` FOREIGN KEY (`DEPID`) REFERENCES `dependents` (`DEPID`),
  ADD CONSTRAINT `FK_SLIP_DOC` FOREIGN KEY (`DOCID`) REFERENCES `doctor` (`DOCID`),
  ADD CONSTRAINT `FK_SLIP_EMP` FOREIGN KEY (`EMPID`) REFERENCES `employee` (`EMPID`),
  ADD CONSTRAINT `FK_SLIP_TOKEN` FOREIGN KEY (`TOKENID`) REFERENCES `token` (`TOKENID`);


ALTER TABLE `token`
  ADD CONSTRAINT `FK_TOKEN_DEP` FOREIGN KEY (`DEPID`) REFERENCES `dependents` (`DEPID`),
  ADD CONSTRAINT `FK_TOKEN_DOC` FOREIGN KEY (`DOCID`) REFERENCES `doctor` (`DOCID`),
  ADD CONSTRAINT `FK_TOKEN_EMP` FOREIGN KEY (`EMPID`) REFERENCES `employee` (`EMPID`);
COMMIT;


